/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubjectsIndexRouteImport } from './routes/subjects/index'
import { Route as NotesIndexRouteImport } from './routes/notes/index'
import { Route as NotesNoteIdRouteImport } from './routes/notes/$noteId'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as SubjectsSubjectIdIndexRouteImport } from './routes/subjects/$subjectId/index'
import { Route as SubjectsSubjectIdCategoryIdIndexRouteImport } from './routes/subjects/$subjectId/$categoryId/index'
import { Route as SubjectsSubjectIdCategoryIdTopicIdRouteImport } from './routes/subjects/$subjectId/$categoryId/$topicId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsIndexRoute = SubjectsIndexRouteImport.update({
  id: '/subjects/',
  path: '/subjects/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIndexRoute = NotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesNoteIdRoute = NotesNoteIdRouteImport.update({
  id: '/notes/$noteId',
  path: '/notes/$noteId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsSubjectIdIndexRoute = SubjectsSubjectIdIndexRouteImport.update({
  id: '/subjects/$subjectId/',
  path: '/subjects/$subjectId/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsSubjectIdCategoryIdIndexRoute =
  SubjectsSubjectIdCategoryIdIndexRouteImport.update({
    id: '/subjects/$subjectId/$categoryId/',
    path: '/subjects/$subjectId/$categoryId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const SubjectsSubjectIdCategoryIdTopicIdRoute =
  SubjectsSubjectIdCategoryIdTopicIdRouteImport.update({
    id: '/subjects/$subjectId/$categoryId/$topicId',
    path: '/subjects/$subjectId/$categoryId/$topicId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/notes/': typeof NotesIndexRoute
  '/subjects/': typeof SubjectsIndexRoute
  '/subjects/$subjectId/': typeof SubjectsSubjectIdIndexRoute
  '/subjects/$subjectId/$categoryId/$topicId': typeof SubjectsSubjectIdCategoryIdTopicIdRoute
  '/subjects/$subjectId/$categoryId/': typeof SubjectsSubjectIdCategoryIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/notes': typeof NotesIndexRoute
  '/subjects': typeof SubjectsIndexRoute
  '/subjects/$subjectId': typeof SubjectsSubjectIdIndexRoute
  '/subjects/$subjectId/$categoryId/$topicId': typeof SubjectsSubjectIdCategoryIdTopicIdRoute
  '/subjects/$subjectId/$categoryId': typeof SubjectsSubjectIdCategoryIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/notes/': typeof NotesIndexRoute
  '/subjects/': typeof SubjectsIndexRoute
  '/subjects/$subjectId/': typeof SubjectsSubjectIdIndexRoute
  '/subjects/$subjectId/$categoryId/$topicId': typeof SubjectsSubjectIdCategoryIdTopicIdRoute
  '/subjects/$subjectId/$categoryId/': typeof SubjectsSubjectIdCategoryIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/auth/callback'
    | '/notes/$noteId'
    | '/notes/'
    | '/subjects/'
    | '/subjects/$subjectId/'
    | '/subjects/$subjectId/$categoryId/$topicId'
    | '/subjects/$subjectId/$categoryId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/auth/callback'
    | '/notes/$noteId'
    | '/notes'
    | '/subjects'
    | '/subjects/$subjectId'
    | '/subjects/$subjectId/$categoryId/$topicId'
    | '/subjects/$subjectId/$categoryId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/auth/callback'
    | '/notes/$noteId'
    | '/notes/'
    | '/subjects/'
    | '/subjects/$subjectId/'
    | '/subjects/$subjectId/$categoryId/$topicId'
    | '/subjects/$subjectId/$categoryId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  NotesNoteIdRoute: typeof NotesNoteIdRoute
  NotesIndexRoute: typeof NotesIndexRoute
  SubjectsIndexRoute: typeof SubjectsIndexRoute
  SubjectsSubjectIdIndexRoute: typeof SubjectsSubjectIdIndexRoute
  SubjectsSubjectIdCategoryIdTopicIdRoute: typeof SubjectsSubjectIdCategoryIdTopicIdRoute
  SubjectsSubjectIdCategoryIdIndexRoute: typeof SubjectsSubjectIdCategoryIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/': {
      id: '/subjects/'
      path: '/subjects'
      fullPath: '/subjects/'
      preLoaderRoute: typeof SubjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/': {
      id: '/notes/'
      path: '/notes'
      fullPath: '/notes/'
      preLoaderRoute: typeof NotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$noteId': {
      id: '/notes/$noteId'
      path: '/notes/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof NotesNoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/$subjectId/': {
      id: '/subjects/$subjectId/'
      path: '/subjects/$subjectId'
      fullPath: '/subjects/$subjectId/'
      preLoaderRoute: typeof SubjectsSubjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/$subjectId/$categoryId/': {
      id: '/subjects/$subjectId/$categoryId/'
      path: '/subjects/$subjectId/$categoryId'
      fullPath: '/subjects/$subjectId/$categoryId/'
      preLoaderRoute: typeof SubjectsSubjectIdCategoryIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/$subjectId/$categoryId/$topicId': {
      id: '/subjects/$subjectId/$categoryId/$topicId'
      path: '/subjects/$subjectId/$categoryId/$topicId'
      fullPath: '/subjects/$subjectId/$categoryId/$topicId'
      preLoaderRoute: typeof SubjectsSubjectIdCategoryIdTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  NotesNoteIdRoute: NotesNoteIdRoute,
  NotesIndexRoute: NotesIndexRoute,
  SubjectsIndexRoute: SubjectsIndexRoute,
  SubjectsSubjectIdIndexRoute: SubjectsSubjectIdIndexRoute,
  SubjectsSubjectIdCategoryIdTopicIdRoute:
    SubjectsSubjectIdCategoryIdTopicIdRoute,
  SubjectsSubjectIdCategoryIdIndexRoute: SubjectsSubjectIdCategoryIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
