/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubjectsIndexRouteImport } from './routes/subjects/index'
import { Route as NotesIndexRouteImport } from './routes/notes/index'
import { Route as EditIndexRouteImport } from './routes/edit/index'
import { Route as DomainsIndexRouteImport } from './routes/domains/index'
import { Route as NotesNoteIdRouteImport } from './routes/notes/$noteId'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as SubjectsSubjectIdIndexRouteImport } from './routes/subjects/$subjectId/index'
import { Route as SubjectsSubjectIdCategoryIdIndexRouteImport } from './routes/subjects/$subjectId/$categoryId/index'
import { Route as DomainsDomainIdSubjectsIndexRouteImport } from './routes/domains/$domainId/subjects/index'
import { Route as SubjectsSubjectIdCategoryIdTopicIdRouteImport } from './routes/subjects/$subjectId/$categoryId/$topicId'
import { Route as DomainsDomainIdSubjectsSubjectIdIndexRouteImport } from './routes/domains/$domainId/subjects/$subjectId/index'
import { Route as DomainsDomainIdSubjectsSubjectIdEditRouteImport } from './routes/domains/$domainId/subjects/$subjectId/edit'
import { Route as DomainsDomainIdSubjectsSubjectIdCategoryIdIndexRouteImport } from './routes/domains/$domainId/subjects/$subjectId/$categoryId/index'
import { Route as DomainsDomainIdSubjectsSubjectIdCategoryIdTopicIdRouteImport } from './routes/domains/$domainId/subjects/$subjectId/$categoryId/$topicId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsIndexRoute = SubjectsIndexRouteImport.update({
  id: '/subjects/',
  path: '/subjects/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIndexRoute = NotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditIndexRoute = EditIndexRouteImport.update({
  id: '/edit/',
  path: '/edit/',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsIndexRoute = DomainsIndexRouteImport.update({
  id: '/domains/',
  path: '/domains/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesNoteIdRoute = NotesNoteIdRouteImport.update({
  id: '/notes/$noteId',
  path: '/notes/$noteId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsSubjectIdIndexRoute = SubjectsSubjectIdIndexRouteImport.update({
  id: '/subjects/$subjectId/',
  path: '/subjects/$subjectId/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsSubjectIdCategoryIdIndexRoute =
  SubjectsSubjectIdCategoryIdIndexRouteImport.update({
    id: '/subjects/$subjectId/$categoryId/',
    path: '/subjects/$subjectId/$categoryId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DomainsDomainIdSubjectsIndexRoute =
  DomainsDomainIdSubjectsIndexRouteImport.update({
    id: '/domains/$domainId/subjects/',
    path: '/domains/$domainId/subjects/',
    getParentRoute: () => rootRouteImport,
  } as any)
const SubjectsSubjectIdCategoryIdTopicIdRoute =
  SubjectsSubjectIdCategoryIdTopicIdRouteImport.update({
    id: '/subjects/$subjectId/$categoryId/$topicId',
    path: '/subjects/$subjectId/$categoryId/$topicId',
    getParentRoute: () => rootRouteImport,
  } as any)
const DomainsDomainIdSubjectsSubjectIdIndexRoute =
  DomainsDomainIdSubjectsSubjectIdIndexRouteImport.update({
    id: '/domains/$domainId/subjects/$subjectId/',
    path: '/domains/$domainId/subjects/$subjectId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DomainsDomainIdSubjectsSubjectIdEditRoute =
  DomainsDomainIdSubjectsSubjectIdEditRouteImport.update({
    id: '/domains/$domainId/subjects/$subjectId/edit',
    path: '/domains/$domainId/subjects/$subjectId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const DomainsDomainIdSubjectsSubjectIdCategoryIdIndexRoute =
  DomainsDomainIdSubjectsSubjectIdCategoryIdIndexRouteImport.update({
    id: '/domains/$domainId/subjects/$subjectId/$categoryId/',
    path: '/domains/$domainId/subjects/$subjectId/$categoryId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DomainsDomainIdSubjectsSubjectIdCategoryIdTopicIdRoute =
  DomainsDomainIdSubjectsSubjectIdCategoryIdTopicIdRouteImport.update({
    id: '/domains/$domainId/subjects/$subjectId/$categoryId/$topicId',
    path: '/domains/$domainId/subjects/$subjectId/$categoryId/$topicId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/review': typeof ReviewRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/domains/': typeof DomainsIndexRoute
  '/edit/': typeof EditIndexRoute
  '/notes/': typeof NotesIndexRoute
  '/subjects/': typeof SubjectsIndexRoute
  '/subjects/$subjectId/': typeof SubjectsSubjectIdIndexRoute
  '/subjects/$subjectId/$categoryId/$topicId': typeof SubjectsSubjectIdCategoryIdTopicIdRoute
  '/domains/$domainId/subjects/': typeof DomainsDomainIdSubjectsIndexRoute
  '/subjects/$subjectId/$categoryId/': typeof SubjectsSubjectIdCategoryIdIndexRoute
  '/domains/$domainId/subjects/$subjectId/edit': typeof DomainsDomainIdSubjectsSubjectIdEditRoute
  '/domains/$domainId/subjects/$subjectId/': typeof DomainsDomainIdSubjectsSubjectIdIndexRoute
  '/domains/$domainId/subjects/$subjectId/$categoryId/$topicId': typeof DomainsDomainIdSubjectsSubjectIdCategoryIdTopicIdRoute
  '/domains/$domainId/subjects/$subjectId/$categoryId/': typeof DomainsDomainIdSubjectsSubjectIdCategoryIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/review': typeof ReviewRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/domains': typeof DomainsIndexRoute
  '/edit': typeof EditIndexRoute
  '/notes': typeof NotesIndexRoute
  '/subjects': typeof SubjectsIndexRoute
  '/subjects/$subjectId': typeof SubjectsSubjectIdIndexRoute
  '/subjects/$subjectId/$categoryId/$topicId': typeof SubjectsSubjectIdCategoryIdTopicIdRoute
  '/domains/$domainId/subjects': typeof DomainsDomainIdSubjectsIndexRoute
  '/subjects/$subjectId/$categoryId': typeof SubjectsSubjectIdCategoryIdIndexRoute
  '/domains/$domainId/subjects/$subjectId/edit': typeof DomainsDomainIdSubjectsSubjectIdEditRoute
  '/domains/$domainId/subjects/$subjectId': typeof DomainsDomainIdSubjectsSubjectIdIndexRoute
  '/domains/$domainId/subjects/$subjectId/$categoryId/$topicId': typeof DomainsDomainIdSubjectsSubjectIdCategoryIdTopicIdRoute
  '/domains/$domainId/subjects/$subjectId/$categoryId': typeof DomainsDomainIdSubjectsSubjectIdCategoryIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/review': typeof ReviewRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/domains/': typeof DomainsIndexRoute
  '/edit/': typeof EditIndexRoute
  '/notes/': typeof NotesIndexRoute
  '/subjects/': typeof SubjectsIndexRoute
  '/subjects/$subjectId/': typeof SubjectsSubjectIdIndexRoute
  '/subjects/$subjectId/$categoryId/$topicId': typeof SubjectsSubjectIdCategoryIdTopicIdRoute
  '/domains/$domainId/subjects/': typeof DomainsDomainIdSubjectsIndexRoute
  '/subjects/$subjectId/$categoryId/': typeof SubjectsSubjectIdCategoryIdIndexRoute
  '/domains/$domainId/subjects/$subjectId/edit': typeof DomainsDomainIdSubjectsSubjectIdEditRoute
  '/domains/$domainId/subjects/$subjectId/': typeof DomainsDomainIdSubjectsSubjectIdIndexRoute
  '/domains/$domainId/subjects/$subjectId/$categoryId/$topicId': typeof DomainsDomainIdSubjectsSubjectIdCategoryIdTopicIdRoute
  '/domains/$domainId/subjects/$subjectId/$categoryId/': typeof DomainsDomainIdSubjectsSubjectIdCategoryIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/privacy'
    | '/review'
    | '/terms'
    | '/auth/callback'
    | '/notes/$noteId'
    | '/domains/'
    | '/edit/'
    | '/notes/'
    | '/subjects/'
    | '/subjects/$subjectId/'
    | '/subjects/$subjectId/$categoryId/$topicId'
    | '/domains/$domainId/subjects/'
    | '/subjects/$subjectId/$categoryId/'
    | '/domains/$domainId/subjects/$subjectId/edit'
    | '/domains/$domainId/subjects/$subjectId/'
    | '/domains/$domainId/subjects/$subjectId/$categoryId/$topicId'
    | '/domains/$domainId/subjects/$subjectId/$categoryId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/privacy'
    | '/review'
    | '/terms'
    | '/auth/callback'
    | '/notes/$noteId'
    | '/domains'
    | '/edit'
    | '/notes'
    | '/subjects'
    | '/subjects/$subjectId'
    | '/subjects/$subjectId/$categoryId/$topicId'
    | '/domains/$domainId/subjects'
    | '/subjects/$subjectId/$categoryId'
    | '/domains/$domainId/subjects/$subjectId/edit'
    | '/domains/$domainId/subjects/$subjectId'
    | '/domains/$domainId/subjects/$subjectId/$categoryId/$topicId'
    | '/domains/$domainId/subjects/$subjectId/$categoryId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/privacy'
    | '/review'
    | '/terms'
    | '/auth/callback'
    | '/notes/$noteId'
    | '/domains/'
    | '/edit/'
    | '/notes/'
    | '/subjects/'
    | '/subjects/$subjectId/'
    | '/subjects/$subjectId/$categoryId/$topicId'
    | '/domains/$domainId/subjects/'
    | '/subjects/$subjectId/$categoryId/'
    | '/domains/$domainId/subjects/$subjectId/edit'
    | '/domains/$domainId/subjects/$subjectId/'
    | '/domains/$domainId/subjects/$subjectId/$categoryId/$topicId'
    | '/domains/$domainId/subjects/$subjectId/$categoryId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ReviewRoute: typeof ReviewRoute
  TermsRoute: typeof TermsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  NotesNoteIdRoute: typeof NotesNoteIdRoute
  DomainsIndexRoute: typeof DomainsIndexRoute
  EditIndexRoute: typeof EditIndexRoute
  NotesIndexRoute: typeof NotesIndexRoute
  SubjectsIndexRoute: typeof SubjectsIndexRoute
  SubjectsSubjectIdIndexRoute: typeof SubjectsSubjectIdIndexRoute
  SubjectsSubjectIdCategoryIdTopicIdRoute: typeof SubjectsSubjectIdCategoryIdTopicIdRoute
  DomainsDomainIdSubjectsIndexRoute: typeof DomainsDomainIdSubjectsIndexRoute
  SubjectsSubjectIdCategoryIdIndexRoute: typeof SubjectsSubjectIdCategoryIdIndexRoute
  DomainsDomainIdSubjectsSubjectIdEditRoute: typeof DomainsDomainIdSubjectsSubjectIdEditRoute
  DomainsDomainIdSubjectsSubjectIdIndexRoute: typeof DomainsDomainIdSubjectsSubjectIdIndexRoute
  DomainsDomainIdSubjectsSubjectIdCategoryIdTopicIdRoute: typeof DomainsDomainIdSubjectsSubjectIdCategoryIdTopicIdRoute
  DomainsDomainIdSubjectsSubjectIdCategoryIdIndexRoute: typeof DomainsDomainIdSubjectsSubjectIdCategoryIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/': {
      id: '/subjects/'
      path: '/subjects'
      fullPath: '/subjects/'
      preLoaderRoute: typeof SubjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/': {
      id: '/notes/'
      path: '/notes'
      fullPath: '/notes/'
      preLoaderRoute: typeof NotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit/': {
      id: '/edit/'
      path: '/edit'
      fullPath: '/edit/'
      preLoaderRoute: typeof EditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains/': {
      id: '/domains/'
      path: '/domains'
      fullPath: '/domains/'
      preLoaderRoute: typeof DomainsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$noteId': {
      id: '/notes/$noteId'
      path: '/notes/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof NotesNoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/$subjectId/': {
      id: '/subjects/$subjectId/'
      path: '/subjects/$subjectId'
      fullPath: '/subjects/$subjectId/'
      preLoaderRoute: typeof SubjectsSubjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/$subjectId/$categoryId/': {
      id: '/subjects/$subjectId/$categoryId/'
      path: '/subjects/$subjectId/$categoryId'
      fullPath: '/subjects/$subjectId/$categoryId/'
      preLoaderRoute: typeof SubjectsSubjectIdCategoryIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains/$domainId/subjects/': {
      id: '/domains/$domainId/subjects/'
      path: '/domains/$domainId/subjects'
      fullPath: '/domains/$domainId/subjects/'
      preLoaderRoute: typeof DomainsDomainIdSubjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/$subjectId/$categoryId/$topicId': {
      id: '/subjects/$subjectId/$categoryId/$topicId'
      path: '/subjects/$subjectId/$categoryId/$topicId'
      fullPath: '/subjects/$subjectId/$categoryId/$topicId'
      preLoaderRoute: typeof SubjectsSubjectIdCategoryIdTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains/$domainId/subjects/$subjectId/': {
      id: '/domains/$domainId/subjects/$subjectId/'
      path: '/domains/$domainId/subjects/$subjectId'
      fullPath: '/domains/$domainId/subjects/$subjectId/'
      preLoaderRoute: typeof DomainsDomainIdSubjectsSubjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains/$domainId/subjects/$subjectId/edit': {
      id: '/domains/$domainId/subjects/$subjectId/edit'
      path: '/domains/$domainId/subjects/$subjectId/edit'
      fullPath: '/domains/$domainId/subjects/$subjectId/edit'
      preLoaderRoute: typeof DomainsDomainIdSubjectsSubjectIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains/$domainId/subjects/$subjectId/$categoryId/': {
      id: '/domains/$domainId/subjects/$subjectId/$categoryId/'
      path: '/domains/$domainId/subjects/$subjectId/$categoryId'
      fullPath: '/domains/$domainId/subjects/$subjectId/$categoryId/'
      preLoaderRoute: typeof DomainsDomainIdSubjectsSubjectIdCategoryIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains/$domainId/subjects/$subjectId/$categoryId/$topicId': {
      id: '/domains/$domainId/subjects/$subjectId/$categoryId/$topicId'
      path: '/domains/$domainId/subjects/$subjectId/$categoryId/$topicId'
      fullPath: '/domains/$domainId/subjects/$subjectId/$categoryId/$topicId'
      preLoaderRoute: typeof DomainsDomainIdSubjectsSubjectIdCategoryIdTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ReviewRoute: ReviewRoute,
  TermsRoute: TermsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  NotesNoteIdRoute: NotesNoteIdRoute,
  DomainsIndexRoute: DomainsIndexRoute,
  EditIndexRoute: EditIndexRoute,
  NotesIndexRoute: NotesIndexRoute,
  SubjectsIndexRoute: SubjectsIndexRoute,
  SubjectsSubjectIdIndexRoute: SubjectsSubjectIdIndexRoute,
  SubjectsSubjectIdCategoryIdTopicIdRoute:
    SubjectsSubjectIdCategoryIdTopicIdRoute,
  DomainsDomainIdSubjectsIndexRoute: DomainsDomainIdSubjectsIndexRoute,
  SubjectsSubjectIdCategoryIdIndexRoute: SubjectsSubjectIdCategoryIdIndexRoute,
  DomainsDomainIdSubjectsSubjectIdEditRoute:
    DomainsDomainIdSubjectsSubjectIdEditRoute,
  DomainsDomainIdSubjectsSubjectIdIndexRoute:
    DomainsDomainIdSubjectsSubjectIdIndexRoute,
  DomainsDomainIdSubjectsSubjectIdCategoryIdTopicIdRoute:
    DomainsDomainIdSubjectsSubjectIdCategoryIdTopicIdRoute,
  DomainsDomainIdSubjectsSubjectIdCategoryIdIndexRoute:
    DomainsDomainIdSubjectsSubjectIdCategoryIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
